replicaCount: 3

image:
  repository: 113645088585.dkr.ecr.us-east-1.amazonaws.com/tech-challenge-2-hello-flask
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 12
  cpuUtilization: 50
  memoryUtilization: 50

ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  port: 80